version: "3.9"

services:
  go: &go
    build:
      context: .
      dockerfile: ./Dockerfile
    image: observerly/nocturnal:latest
    container_name: observerly_nocturnal
    ports:
      - "8103:8103"
    env_file:
      - .env
    command:
      - "./app"