version: "3.9"

services:
  api: &api
    build:
      context: .
      dockerfile: ./Dockerfile
    image: observerly/nocturnal:latest
    container_name: observerly_nocturnal
    ports:
      - "8103:8103"
    env_file:
      - .env
    command:
      - "/app/start.sh"